### ISSUE TITLE
not working with pyenv

### ISSUE THREAD

**Issue by Poil** [E3V3A/pip-date#10]
Hi,

It doesn't seem to work in a pyenv/virtualenv environment

**Environment**

* pip version: `pip 19.2.1 from /home/xxxxxx/.local/share/virtualenvs/bo-JcXeAW25/lib/python3.6/site-packages/pip (python 3.6)`
* Python version: `Python 3.6.8`
* OS: Ubuntu 19.04
* pyenv : pyenv 1.2.12-2-geb68ec94

**Description**
```
$ pip install pip-date
$ pip-date


Using mTime for Linux FS

Traceback (most recent call last):
  File "/home/bdupuis/.local/share/virtualenvs/bo-JcXeAW25/bin/pip-date", line 264, in <module>
    site_loc = site.getsitepackages()           # [...]
AttributeError: module 'site' has no attribute 'getsitepackages'
```

**Comment by Poil** [comment]
sorry, virtualenv copy a non up2date sites.py.

**Comment by Poil** [comment]
https://github.com/E3V3A/pip-date/pull/11

**Comment by E3V3A** [comment]
Hi @Poil 
Thanks for that PR! :1st_place_medal: 

Looks good but I need to test before merging and add to the new relaease. 
Sorry, but I've kind of forgotten about this repo in the last few months, so no ETA yet.
