### ISSUE TITLE
Add *.py extension to all scripts to simplify Windows compatibility

### ISSUE THREAD

**Issue by E3V3A** [E3V3A/pip-date#22]
Windows still doesn't like files without extensions, and hacking around it with (windows python) *shebangs* is tricky and not easy for most. Adding wrappers to each script is also too much work.

I will add the extensions to all files.

**Comment by wimglenn** [comment]
Hey there, @E3V3A  this totally breaks the package for Linux and macOS users.  

```
$ pip install -q pip-date
$ pip-date
zsh: command not found: pip-date
$ pip-date.py
zsh: permission denied: pip-date.py
```

You'll need to set the executable bits on the scripts.  But I don't recommend to package scripts like this at all, tbh, it's much better to use the console_scripts entrypoint group of setuptools and just let pip generate the wrappers at install time. I'm not sure what you mean by "too much work", it's just a one-line change in the `setup.py` pretty much ..
